using System.Collections;
using System.Collections.Generic;
using UnityEngine;

[RequireComponent(typeof(Collider))]
public class NPCDialog : MonoBehaviour
{
    protected Collider m_collider;
    protected bool m_showing;

    protected virtual void Awake()
    {
        m_collider = GetComponent<Collider>();
        m_collider.isTrigger = true;
    }

    protected virtual void OnTriggerStay(Collider other)
    {
        if (other.CompareTag(GameTags.Player))
        {
            ShowTint();//鞫刻슥빳숩(흔渴흙enter)

            if (true)//渴흙슥빳숩
            {
                ShowDialog();//뎐놔뚤뺐움
            }
        }
    }

    protected virtual void OnTriggerExit(Collider other)
    {
        if (other.CompareTag(GameTags.Player))
        {
            HideTint();//잼역茶꾜슥빳숩
        }
    }
}
